language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4

before_install:
  - composer self-update

before_script:
  - mkdir -p build/logs

install:
  - cd src && composer install --no-interaction

script:
  - php ./src/vendor/bin/phpunit --configuration=phpunit.xml
